from __future__ import annotations

from datetime import datetime, timezone

_SEVERITY_ORDER = ["critical", "high", "medium", "low", "info"]
_SEVERITY_ICON = {
    "critical": "🔴", "high": "🟠", "medium": "🟡", "low": "🔵", "info": "⚪",
}


def render(
    *,
    aws_account_id: str | None,
    resource_count: int,
    severity_counts: dict[str, int],
    summary: str,
    findings: list[dict],
    mermaid_map: str,
    completed_at: datetime | None = None,
) -> str:
    completed_at = completed_at or datetime.now(timezone.utc)
    sections = [
        _header(aws_account_id, resource_count, severity_counts, findings, completed_at),
        _summary(summary),
        _mermaid(mermaid_map),
        _findings(findings),
        "---\n\n_Generated by ian-aws-audit._",
    ]
    return "\n\n".join(s for s in sections if s)


def _header(account_id, resource_count, sev_counts, findings, completed_at) -> str:
    account = f"AWS {account_id}" if account_id else "AWS account"
    generated = completed_at.strftime("%Y-%m-%d %H:%M UTC")
    total = len(findings or [])
    counts_inline = ", ".join(
        f"{sev_counts.get(s, 0)} {s}" for s in _SEVERITY_ORDER if sev_counts.get(s, 0)
    ) or "none"
    return (
        f"# Infrastructure Audit — {account}\n\n"
        f"- **Generated:** {generated}\n"
        f"- **Resources scanned:** {resource_count}\n"
        f"- **Findings:** {total} ({counts_inline})"
    )


def _summary(summary: str) -> str:
    return f"## Summary\n\n{summary}" if summary else ""


def _mermaid(mermaid_map: str) -> str:
    m = (mermaid_map or "").strip()
    return f"## Infrastructure Map\n\n```mermaid\n{m}\n```" if m else ""


def _findings(findings: list[dict]) -> str:
    if not findings:
        return "## Findings\n\nNo findings recorded."

    grouped: dict[str, list[dict]] = {}
    for f in findings:
        grouped.setdefault(str(f.get("severity", "")).lower(), []).append(f)
    ordered = [f for sev in _SEVERITY_ORDER for f in grouped.get(sev, [])]

    lines = ["## Findings"]
    for idx, finding in enumerate(ordered, start=1):
        sev = str(finding.get("severity", "")).lower()
        icon = _SEVERITY_ICON.get(sev, "•")
        category = str(finding.get("category", "")).title()
        title = finding.get("title", "")
        description = finding.get("description", "")
        recommendation = finding.get("recommendation", "")
        affected = finding.get("resources_affected") or []

        lines.append("")
        lines.append(f"### {idx}. {icon} {title}")
        lines.append(f"*{sev.title()} · {category}*")
        lines.append("")
        lines.append(description)
        if recommendation:
            lines.append("")
            lines.append(f"**Recommendation:** {recommendation}")
        if affected:
            shown = ", ".join(f"`{r}`" for r in affected[:10])
            extra = f" (+{len(affected) - 10} more)" if len(affected) > 10 else ""
            lines.append("")
            lines.append(f"**Affected resources:** {shown}{extra}")
    return "\n".join(lines)
